server:
  port: 7002
spring:
  application:
    name: eureka-provider1
  cloud:
    client:
      ip-config: 192.168.47.1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://server1:7000/eureka/
  instance:
    hostname: localhost